### ISSUE TITLE
无法拉取到 0.0.20 版本的 docker 镜像

### ISSUE THREAD

**Issue by ximi-co** [gocrane/crane-scheduler#12]
您好，我部署 0.0.20 版本的时候提示没有找到镜像，请问是我部署的过程有问题还是什么问题呢？
k8s 版本：v1.21
helm 版本：v3.3.3

部署流程：
1. 直接使用 helm 部署，失败
![图片](https://user-images.githubusercontent.com/61510761/180139356-3c04ebaf-2b5d-4912-bbb5-a4043e8ca4e6.png)

2. 将项目克隆下来，使用 kubectl.exe apply -f rbac.yaml 部署成功，在 k8s 服务器上使用下面命令修改版本失败
` KUBE_EDITOR="sed -i 's/v1beta2/v1beta1/g'" kubectl edit cm scheduler-config -n crane-system && KUBE_EDITOR="sed -i 's/0.0.23/0.0.20/g'" kubectl edit deploy crane-scheduler -n crane-system`
![图片](https://user-images.githubusercontent.com/61510761/180153968-3fe72f39-f60b-4b34-9fd4-88f5355aecfd.png)
![图片](https://user-images.githubusercontent.com/61510761/180154586-a397d466-2d6b-46dc-b7db-71840566e53d.png)

3. 直接修改 yaml 文件部署，部署后提示没有找到镜像

将 git\crane-scheduler\deploy\manifests\scheduler-config.yaml 中的 v1beta2 修改为 v1beta1
> apiVersion: kubescheduler.config.k8s.io/v1beta1
> kind: KubeSchedulerConfiguration
> leaderElection:
> ......

将 git\crane-scheduler\deploy\controller\deployment.yaml 中的 0.0.23 修改为 0.0.20
> ......
>           command:
>             - /controller
>             - --policy-config-path=/data/policy.yaml
>             - --prometheus-address=PROMETHEUS_ADDRESS
>           image: docker.io/gocrane/crane-scheduler-controller:0.0.20
>           imagePullPolicy: IfNotPresent
>           volumeMounts:
>             - mountPath: /data
>               name: dynamic-scheduler-policy
> ......

提示没有找到镜像
![图片](https://user-images.githubusercontent.com/61510761/180350700-c435a226-dadb-4d84-9d21-d0b7ab523589.png)

**Comment by autumn0207** [comment]
> 您好，我部署 0.0.20 版本的时候提示没有找到镜像，请问是我部署的过程有问题还是什么问题呢？ k8s 版本：v1.21 helm 版本：v3.3.3
> 
> 部署流程：
> 
> 1. 直接使用 helm 部署，失败
>    ![图片](https://user-images.githubusercontent.com/61510761/180139356-3c04ebaf-2b5d-4912-bbb5-a4043e8ca4e6.png)
> 2. 将项目克隆下来，使用 kubectl.exe apply -f rbac.yaml 部署成功，在 k8s 服务器上使用下面命令修改版本失败
>    ` KUBE_EDITOR="sed -i 's/v1beta2/v1beta1/g'" kubectl edit cm scheduler-config -n crane-system && KUBE_EDITOR="sed -i 's/0.0.23/0.0.20/g'" kubectl edit deploy crane-scheduler -n crane-system`
>    ![图片](https://user-images.githubusercontent.com/61510761/180153968-3fe72f39-f60b-4b34-9fd4-88f5355aecfd.png)
>    ![图片](https://user-images.githubusercontent.com/61510761/180154586-a397d466-2d6b-46dc-b7db-71840566e53d.png)
> 3. 直接修改 yaml 文件部署，部署后提示没有找到镜像
> 
> 将 git\crane-scheduler\deploy\manifests\scheduler-config.yaml 中的 v1beta2 修改为 v1beta1
> 
> > apiVersion: kubescheduler.config.k8s.io/v1beta1
> > kind: KubeSchedulerConfiguration
> > leaderElection:
> > ......
> 
> 将 git\crane-scheduler\deploy\controller\deployment.yaml 中的 0.0.23 修改为 0.0.20
> 
> > ......
> > command:
> > - /controller
> > - --policy-config-path=/data/policy.yaml
> > - --prometheus-address=PROMETHEUS_ADDRESS
> > image: docker.io/gocrane/crane-scheduler-controller:0.0.20
> > imagePullPolicy: IfNotPresent
> > volumeMounts:
> > - mountPath: /data
> > name: dynamic-scheduler-policy
> > ......
> 
> 提示没有找到镜像 ![图片](https://user-images.githubusercontent.com/61510761/180350700-c435a226-dadb-4d84-9d21-d0b7ab523589.png)
@ximi-co 
controller 可以使用 0.0.23 的镜像不替换，这个是兼容的

**Comment by ximi-co** [comment]
好的，我已经使用 0.0.23 部署成功了。但是调度上面好像还有点问题，我再测试一下。

**Comment by ximi-co** [comment]
可以使用了，非常感谢
