### ISSUE TITLE
dynamic plugin score is abnormal

### ISSUE THREAD

**Issue by zwForrest** [gocrane/crane-scheduler#14]
## What happened?

applying score defaultWeights on Score plugins: plugin "Dynamic" returns an invalid score -8, it should in the range of [0, 100] after normalizing

## What did you expect to happen?

pod can be scheduled successfully

## How can we reproduce it (as minimally and precisely as possible)?

This problem occurs when the prometheus result times out, but the hotValue is normal.

**Comment by autumn0207** [comment]
> returns an invalid score -8

@zwForrest 
👍  It's a bug, we will fix it asap

**Comment by xieydd** [comment]
have some progress？ @autumn0207

**Comment by zcspk** [comment]
我也遇到这个问题

**Comment by qmhu** [comment]
关注一下:)
