### ISSUE TITLE
scheduler-controller通过ip不通过node name拉取数据  啥时候crane能再次helm发版解决这个问题

### ISSUE THREAD

**Issue by Phoebus888** [gocrane/crane-scheduler#20]
![image](https://user-images.githubusercontent.com/45359605/187041323-3305684c-16f8-4341-8bae-2e7b9b8cd83d.png)
```
还在一直node name报错
```

**Comment by Phoebus888** [comment]
这个通过服务名称能解决吗  我k8s上的prometheus有需要的服务器名称  要不然我需要维护两套prometheus了

**Comment by zcspk** [comment]
hello 请问是helm 部署的吗 ，第二种替换方案如何实现的

**Comment by xieydd** [comment]
I think it is already fixed in https://github.com/gocrane/crane-scheduler/pull/19.
