### ISSUE TITLE
替换默认调度器问题

### ISSUE THREAD

**Issue by zcspk** [gocrane/crane-scheduler#32]
[root@zcsmaster1 manifests]# cat kube-scheduler.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
   # - kube-scheduler
    - /scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=192.168.40.180
    - --config=/etc/kubernetes/kube-scheduler/scheduler-config.yaml
#    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: docker.io/gocrane/crane-scheduler:0.0.20
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.40.180 
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 12
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 192.168.40.180
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
#    - mountPath: /etc/kubernetes/scheduler.conf
#      name: kubeconfig
#      readOnly: true
    - name: scheduler-config
      mountPath: /etc/kubernetes/kube-scheduler
      readOnly: true
    - name: dynamic-scheduler-policy
      mountPath: /etc/kubernetes
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
#  - hostPath:
#      path: /etc/kubernetes/scheduler.conf
#      type: FileOrCreate
#    name: kubeconfig
  - name: scheduler-config
    configMap:
      name: scheduler-config
  - name: dynamic-scheduler-policy
    configMap:
      name: dynamic-scheduler-policy
status: {}

[root@zcsmaster1 manifests]# 

您好 ，对默认的调度器进行替换 ，这种方式一直不成功，可以出一下详细的文档吗？
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  93s                default-scheduler  Successfully assigned kube-system/kube-scheduler to zcsnode2
  Normal   Pulled     36s (x4 over 93s)  kubelet            Container image "docker.io/gocrane/crane-scheduler:0.0.20" already present on machine
  Normal   Created    36s (x4 over 93s)  kubelet            Created container kube-scheduler
  Normal   Started    36s (x4 over 93s)  kubelet            Started container kube-scheduler
  Warning  BackOff    3s (x10 over 91s)  kubelet            Back-off restarting failed container
[root@zcsmaster1 manifests]# kubectl  describe pod kube-scheduler  -n kube-system

Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  53m                    default-scheduler  Successfully assigned kube-system/crane-scheduler-controller-7845b4cbf7-dhrkm to zcsnode2
  Normal   Pulled     52m (x2 over 53m)      kubelet            Container image "docker.io/gocrane/crane-scheduler-controller:0.0.23" already present on machine
  Normal   Created    52m (x2 over 53m)      kubelet            Created container controller
  Normal   Started    52m (x2 over 53m)      kubelet            Started container controller
  Normal   Killing    52m                    kubelet            Container controller failed liveness probe, will be restarted
  Warning  Unhealthy  51m (x5 over 53m)      kubelet            Liveness probe failed: Get "http://10.244.234.118:8090/healthz": dial tcp 10.244.234.118:8090: connect: connection refused
  Warning  BackOff    8m29s (x116 over 46m)  kubelet            Back-off restarting failed container
  Warning  Unhealthy  3m40s (x138 over 53m)  kubelet            Readiness probe failed: Get "http://10.244.234.118:8090/healthz": dial tcp 10.244.234.118:8090: connect: connection refused
[root@zcsmaster1 manifests]#

**Comment by xieydd** [comment]
Is is successful, i found you create an issue about hot value count error, so you have installed the crane-scheduler already?

**Comment by xieydd** [comment]
If needed, i will reopen the issue.
