### ISSUE TITLE
scheduler-controller无法正常运行

### ISSUE THREAD

**Issue by tarakang** [gocrane/crane-scheduler#39]
controller一直重启无法正常Running，查看日志提示如下，但是describe node看是已经成功添加Annotations的
I0201 18:00:43.153543       1 node.go:75] Finished syncing node event "node-2/mem_usage_max_avg_1d" (20.320214ms)
I0201 18:00:43.175135       1 node.go:75] Finished syncing node event "master/mem_usage_max_avg_1d" (21.563645ms)
I0201 18:00:43.197964       1 node.go:75] Finished syncing node event "node-1/mem_usage_max_avg_1d" (22.784592ms)
I0201 18:00:53.119482       1 node.go:75] Finished syncing node event "node-2/cpu_usage_avg_5m" (2.02963ms)
W0201 18:00:53.119507       1 node.go:61] failed to sync this node ["node-2/cpu_usage_avg_5m"]: can not annotate node[node-2]: failed to get data cpu_usage_avg_5m{node-2=}: <nil>
I0201 18:00:53.120460       1 node.go:75] Finished syncing node event "master/cpu_usage_avg_5m" (939.612µs)
W0201 18:00:53.120483       1 node.go:61] failed to sync this node ["master/cpu_usage_avg_5m"]: can not annotate node[master]: failed to get data cpu_usage_avg_5m{master=}: <nil>

**Comment by Gaoning6722** [comment]
W1119 20:52:44.188897       1 node.go:61] failed to sync this node ["k8s-node2/cpu_usage_max_avg_1h"]: can not annotate node[k8s-node2]: failed to get data cpu_usage_max_avg_1h{k8s-node2=}: Post "http://192.168.31.17:30090/api/v1/query": context deadline exceeded
I1119 20:53:14.192007       1 node.go:75] Finished syncing node event "k8s-node1/cpu_usage_max_avg_1h" (30.003083965s)
W1119 20:53:14.192023       1 node.go:61] failed to sync this node ["k8s-node1/cpu_usage_max_avg_1h"]: can not annotate node[k8s-node1]: failed to get data cpu_usage_max_avg_1h{k8s-node1=}: Post "http://192.168.31.17:30090/api/v1/query": context deadline exceeded
I1119 20:53:44.192957       1 node.go:75] Finished syncing node event "node/cpu_usage_max_avg_1h" (30.000903987s)
W1119 20:53:44.192993       1 node.go:61] failed to sync this node ["node/cpu_usage_max_avg_1h"]: can not annotate node[node]: failed to get data cpu_usage_max_avg_1h{node=}: Post "http://192.168.31.17:30090/api/v1/query": context deadline exceeded
I1119 20:54:14.195326       1 node.go:75] Finished syncing node event "k8s-node2/cpu_usage_max_avg_1d" (30.002296671s)
W1119 20:54:14.195444       1 node.go:61] failed to sync this node ["k8s-node2/cpu_usage_max_avg_1d"]: can not annotate node[k8s-node2]: failed to get data cpu_usage_max_avg_1d{k8s-node2=}: Post "http://192.168.31.17:30090/api/v1/query": context deadline exceeded
I1119 20:54:44.198766       1 node.go:75] Finished syncing node event "k8s-node1/cpu_usage_max_avg_1d" (30.003239565s)
W1119 20:54:44.198886       1 node.go:61] failed to sync this node ["k8s-node1/cpu_usage_max_avg_1d"]: can not annotate node[k8s-node1]: failed to get data cpu_usage_max_avg_1d{k8s-node1=}: Post "http://192.168.31.17:30090/api/v1/query": context deadline exceeded
I1119 20:55:14.200925       1 node.go:75] Finished syncing node event "node/cpu_usage_max_avg_1d" (30.001991199s)
W1119 20:55:14.200957       1 node.go:61] failed to sync this node ["node/cpu_usage_max_avg_1d"]: can not annotate node[node]: failed to get data cpu_usage_max_avg_1d{node=}: Post "http://192.168.31.17:30090/api/v1/query": context deadline exceeded
