### ISSUE TITLE
first issue !!

### ISSUE THREAD

**Issue by bretagne-peiqi** [gocrane/crane-scheduler#4]
hello, I deployed crane-scheduler using helm chart. my prometheus svc addr is as below:

but there are error logs in controller pod:

 Post "192.168.15.25/api/v1/query": unsupported protocol scheme ""

can someone explains why it happens. Thanks.

**Comment by bretagne-peiqi** [comment]
besides, how to fix this in scheduler, I have not found the config 
reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: the server could not find the requested resource

**Comment by autumn0207** [comment]
> besides, how to fix this in scheduler, I have not found the config reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: the server could not find the requested resource

Which version of kubernetes are you using?  If the version is from 1.18 to 1.20, you need to modify some configurations:
```bash
KUBE_EDITOR="sed -i 's/v1beta2/v1beta1/g'" kubectl edit cm scheduler-config -n crane-system && KUBE_EDITOR="sed -i 's/0.0.23/0.0.20/g'" kubectl edit deploy crane-scheduler -n crane-system
```

**Comment by autumn0207** [comment]
> my prometheus svc addr is as below

Can you provide complete information?

**Comment by bretagne-peiqi** [comment]
![image](https://user-images.githubusercontent.com/5621794/172742016-eca0c74d-ba6f-477e-8534-bd74cb697498.png)
@autumn0207 thanks.

after I applied the update, new error CSINode resource don't find occurs.

my k8s version is 1.16.6

**Comment by autumn0207** [comment]
> my k8s version is 1.16.6

Sorry, crane-scheduler only supports k8s version 1.18+, and we have never tested this project on version 1.16.


> after I applied the update, new error CSINode resource don't find occurs.

This problem should be caused by the update of CSINode object version, from `v1beta` in v1.16 to `v1` in v1.17+(refer to https://kubernetes-csi.github.io/docs/csi-node-object.html#status).

So, please upgrade k8s first:blush:, otherwise there may be more unexpected problems.

**Comment by Tendrun101** [comment]
I have same problem “Post "192.168.15.25/api/v1/query": unsupported protocol scheme ""”，should I upgrade k8s ？
my k8s version is 1.20，Prometheus is 2.20.0

**Comment by autumn0207** [comment]
@Tendrun101 



> I have same problem “Post "192.168.15.25/api/v1/query": unsupported protocol scheme ""”

Please check where the Prometheus  Address has `http://` prefix, note that only address like `http://address` can take effect.



> should I upgrade k8s

No, 1.20 is OK, and you just need to update some configuration:
```bash
 KUBE_EDITOR="sed -i 's/v1beta2/v1beta1/g'" kubectl edit cm scheduler-config -n crane-system && KUBE_EDITOR="sed -i 's/0.0.23/0.0.20/g'" kubectl edit deploy crane-scheduler -n crane-system
```

**Comment by Tendrun101** [comment]
> @Tendrun101
> 
> > I have same problem “Post "192.168.15.25/api/v1/query": unsupported protocol scheme ""”
> 
> Please check whether the Prometheus Address has `http://` prefix, note that only address like `http://address` can take effect.
> 
> > should I upgrade k8s
> 
> No, 1.20 is OK, and you just need to update some configuration:
> 
> ```shell
>  KUBE_EDITOR="sed -i 's/v1beta2/v1beta1/g'" kubectl edit cm scheduler-config -n crane-system && KUBE_EDITOR="sed -i 's/0.0.23/0.0.20/g'" kubectl edit deploy crane-scheduler -n crane-system
> ```

I made a wrong configuration carelessness。 missing “http://” in my address
