### ISSUE TITLE
replace the k8s scheduler with crane scheduler,new pod pending

### ISSUE THREAD

**Issue by Tendrun101** [gocrane/crane-scheduler#5]
I replace the k8s scheduler with crane scheduler, and then created a new pod. I found the new pod always “Pending”， also no related events info. 

... ...
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule  
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists  
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:          <none>

I can only found some useful info in logs, as as follows：
`I0614 02:18:42.492977       1 eventhandlers.go:118] "Add event for unscheduled pod" pod="kube-system/kubernetes-dashboard-jqhhq"
`

I wonder if the new pod is pop  from the ‘SchedulingQueue’， and how I solved the problem

**Comment by autumn0207** [comment]
> I replace the k8s scheduler with crane scheduler, and then created a new pod. I found the new pod always “Pending”， also no related events info.
> 
> ... ... QoS Class: Burstable Node-Selectors: Tolerations: node-role.kubernetes.io/master:NoSchedule node.kubernetes.io/disk-pressure:NoSchedule op=Exists node.kubernetes.io/memory-pressure:NoSchedule op=Exists node.kubernetes.io/not-ready:NoExecute op=Exists node.kubernetes.io/pid-pressure:NoSchedule op=Exists node.kubernetes.io/unreachable:NoExecute op=Exists node.kubernetes.io/unschedulable:NoSchedule op=Exists Events:
> 
> I can only found some useful info in logs, as as follows： `I0614 02:18:42.492977 1 eventhandlers.go:118] "Add event for unscheduled pod" pod="kube-system/kubernetes-dashboard-jqhhq" `
> 
> I wonder if the new pod is pop from the ‘SchedulingQueue’， and how I solved the problem

which version of k8s are you using?

**Comment by Tendrun101** [comment]
> > I replace the k8s scheduler with crane scheduler, and then created a new pod. I found the new pod always “Pending”， also no related events info.
> > ... ... QoS Class: Burstable Node-Selectors: Tolerations: node-role.kubernetes.io/master:NoSchedule node.kubernetes.io/disk-pressure:NoSchedule op=Exists node.kubernetes.io/memory-pressure:NoSchedule op=Exists node.kubernetes.io/not-ready:NoExecute op=Exists node.kubernetes.io/pid-pressure:NoSchedule op=Exists node.kubernetes.io/unreachable:NoExecute op=Exists node.kubernetes.io/unschedulable:NoSchedule op=Exists Events:
> > I can only found some useful info in logs, as as follows： `I0614 02:18:42.492977 1 eventhandlers.go:118] "Add event for unscheduled pod" pod="kube-system/kubernetes-dashboard-jqhhq" `
> > I wonder if the new pod is pop from the ‘SchedulingQueue’， and how I solved the problem
> 
> which version of k8s are you using?

v1.20.12

**Comment by xieydd** [comment]
If needed, i will reopen the issue.
